# Generated by Django 5.0.3 on 2024-03-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISI', '0006_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='award',
            old_name='Title',
            new_name='title',
        ),
    ]
