# Generated by Django 5.0.3 on 2024-03-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISI', '0007_clientcouncil_rename_title_award_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ChoiceUS')),
            ],
        ),
    ]
