# Generated by Django 5.0.3 on 2024-03-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISI', '0009_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Jobs')),
                ('category', models.CharField(max_length=300)),
                ('vacancy', models.IntegerField()),
                ('requirement', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
            ],
        ),
    ]
