# Generated by Django 5.0.3 on 2024-03-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISI', '0010_jobspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('postName', models.CharField(max_length=600)),
                ('cv', models.FileField(upload_to='CV')),
                ('IdentityCard', models.FileField(upload_to='IdCard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
