# Generated by Django 5.0.3 on 2024-03-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MISI', '0011_appliedcandidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcandidates',
            name='jobsPostTitle',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
