# Generated by Django 5.0.3 on 2024-04-01 06:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MISI', '0012_appliedcandidates_jobsposttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='details_information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
